pub const IMAGES:[(&str, &str); 10] = [("https://miro.medium.com/v2/resize:fit:736/1*YqfVlyCe06DfcPsR3kpYrw.jpeg", "Monkey D. Luffy"),
                                       ("https://i.pinimg.com/originals/77/86/86/778686ed1526f7e13bb82ac0346a5f96.jpg", "Roronoa Zoro"), 
                                       ("https://i.ytimg.com/vi/Q1BqlYsTb7E/maxresdefault.jpg", "Usopp"), 
                                       ("https://static1.cbrimages.com/wordpress/wp-content/uploads/2019/10/Vinsmoke-Sanji.jpg", "Vinsmoke Sanji"),
                                       ("https://upload.wikimedia.org/wikipedia/en/f/f8/Nami_face.jpg", "Nami"),
                                       ("https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/04/chopper-wano-samurai-1915x-1.jpg", "Chopper"),
                                       ("https://images.cgames.de/images/gsgp/290/one-piece-nico-robin_6209985.jpg", "Robin"),
                                       ("https://i.pinimg.com/736x/c6/e0/07/c6e0070680dd9de4fa03be7d719c3cc5.jpg", "Franky"),
                                       ("https://i.pinimg.com/originals/ed/d5/36/edd536243dab449c0cd7c9d483d36b89.jpg",  "Brook"),
                                       ("https://animeargentina.net/wp-content/uploads/2024/04/jinbe-min-1024x640.jpg", "Jinbe")];
